name: Deploy to GCP Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: senior-citizen-app
  REGION: asia-northeast3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 1) gradlew 실행 권한 부여 (exit code 126 방지)
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 2) JAR 빌드
      - name: Build JAR
        run: ./gradlew bootJar

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # 3) 필수 API 활성화
      - name: Enable required APIs
        run: |
          gcloud services enable artifactregistry.googleapis.com
          gcloud services enable run.googleapis.com
          gcloud services enable cloudbuild.googleapis.com

      # 4) Artifact Registry Repository 생성 (이미 존재하면 무시)
      - name: Create Artifact Registry Repository
        run: |
          gcloud artifacts repositories create $SERVICE_NAME \
            --repository-format=docker \
            --location=$REGION || true

      # 5) Artifact Registry용 Docker 인증 설정
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      # 6) Docker 이미지 빌드 및 Artifact Registry로 푸시
      - name: Build and Push to Artifact Registry
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA

      # 7) Cloud Run 배포 (Artifact Registry 이미지 사용)
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --set-env-vars="SPRING_PROFILES_ACTIVE=db" \
            --set-env-vars="NCP_CLIENT_ID=742tyl7pxy" \
            --set-env-vars="NCP_CLIENT_SECRET=${{ secrets.NCP_CLIENT_SECRET }}" \
            --set-env-vars="KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}" \
            --set-env-vars="KAKAO_JS_API_KEY=${{ secrets.KAKAO_JS_API_KEY }}" \
            --set-env-vars="DB_URL=${{ secrets.DB_URL }}" \
            --set-env-vars="DB_USERNAME=${{ secrets.DB_USERNAME }}" \
            --set-env-vars="DB_PASSWORD=${{ secrets.DB_PASSWORD }}"