

name: Deploy to GCP Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: senior-citizen-app
  REGION: asia-northeast3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build JAR
        run: ./gradlew bootJar

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify authentication
        run: |
          gcloud auth list
          gcloud config list project

      - name: Create Artifact Registry Repository
        run: |
          gcloud artifacts repositories create $SERVICE_NAME \
            --repository-format=docker \
            --location=$REGION || true

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build and Push to Artifact Registry
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --memory=2Gi \
            --cpu=2 \
            --timeout=900 \
            --port=8080 \
            --max-instances=10 \
            --set-env-vars="SPRING_PROFILES_ACTIVE=db" \
            --set-env-vars="SERVER_PORT=8080" \
            --set-env-vars="JAVA_OPTS=-Xmx1536m -Xms512m" \
            --set-env-vars="NCP_CLIENT_ID=742tyl7pxy" \
            --set-env-vars="NCP_CLIENT_SECRET=${{ secrets.NCP_CLIENT_SECRET }}" \
            --set-env-vars="KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}" \
            --set-env-vars="KAKAO_JS_API_KEY=${{ secrets.KAKAO_JS_API_KEY }}" \
            --set-env-vars="DB_URL=${{ secrets.DB_URL }}" \
            --set-env-vars="DB_USERNAME=${{ secrets.DB_USERNAME }}" \
            --set-env-vars="DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
